name: 'GitHub Actions Test Bot'

on:
  push:
  schedule:
    - cron: '*/10  * * * *'

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v1
      - name: 'Send Message'
        run: bash ./message.sh